### ISSUE TITLE
Hosting+1.52 verzia A3

### ISSUE THREAD

**Issue by AnonymCecil** [redoper/CZ-SK-Altis-Life#3]
Tákže všetci serú na váš server 1. z dôvodu že je to na verzií 1.52 len veľmi málo ľudí si to stiahne 2. americký hosting 200 ping keď už si to niekto stiahne tak s tým bude mať problémy s pingom nebude môcť dobre rozprávať do hry , nikto mu nebude rozumieť

**Comment by rimmoncze** [comment]
Server je v holandsku, ping na nej mam 20 ;) provoz zatim uplne bez problemu.

V soucasny dobe je 1.54 nerealna.

Sent from my Windows Phone
________________________________

**Comment by redoper** [comment]
Bohužel na verzi 1.54 servery padají a jsou s ní obrovské problémy. Na aktuální verzi pojedeme, až BIS vydá opravný patch.

Co se týče hostingu, tak pingy jsou úplně v pohodě a je hostovaný v Holadsku, jen má americkou IP adresu, protože provider je nejmenovaná amerucký firma ;).
