### ISSUE TITLE
Zvyšovanie cien , pridávanie vecí 

### ISSUE THREAD

**Issue by AnonymCecil** [redoper/CZ-SK-Altis-Life#4]
No čo som si ja všimol tak poslednou dobousa zvýšily ceny a vraj z dôvodu že všetci mali všetko , teraz nikto nemá nič a asi z tohoto dôvodu nikto nehrá na serveri , taký tempest ktorý stál 1 500 000 (a to som si myslel že je drahý ) teraz stojí cez 3 milióny , uran sa predáva len po 6200 , Budú sa pridávať aj iné drogy ako je hašiš , METH ?

**Comment by redoper** [comment]
Možná časem, teď pracujeme ještě na dalších věcech. Máme celkem dlouhý seznam :).

Jinak ceny byly zvýšeny ne proto, že všichni měli vše, ale protože bylo možné už během dvou dní vydělat na cokoliv a co by jsi pak chtěl dělat? :)

**Comment by AnonymCecil** [comment]
a ten zoznam bude zverejnený , a po tých dvoch dňach by som šiel napríklad na banku

**Comment by redoper** [comment]
To můžeš teoreticky i dřív ;).

Co se týče toho seznam, tak ten současný asi ne, protože by se v našich poznámkách nikdo nevyznal, ale teoreticky bych si to mohl připsat na seznam nových fíčur až budu dělat na novém webu.
